version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://<user>:<password>@db:5432/<database>?schema=public
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: <database>
    ports:
      - "5432:5432"
